CREATE VIEW VPARTICIPANT01 AS 
   SELECT id, NOMPARTICIPANT || ' ' || PRENOMPARTICIPANT as libelle
   FROM PARTICIPANT;

GRANT SELECT  on mdl.VPARTICIPANT01 to APPLIMDL;

create or replace public synonym "VPARTICIPANT" for  "MDL"."VPARTICIPANT";